sudo: false
language: node_js
node_js:
- '5'
- '4.2.3'
- '4'
- '0.12.4'
- '0.12'
- '0.10.24'
- '0.10'

# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"